# Generated by Django 6.0.3 on 2026-03-25 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.FloatField(help_text="Transaction amount")),
                (
                    "source",
                    models.CharField(help_text="Web, Mobile, ATM, POS", max_length=50),
                ),
                ("risk", models.IntegerField(default=0, help_text="Risk score 0-100")),
                (
                    "result",
                    models.CharField(help_text="Fraud/Safe Transaction", max_length=50),
                ),
                (
                    "explanation",
                    models.TextField(blank=True, help_text="AI explanation"),
                ),
                (
                    "sender_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("sender_acc", models.CharField(blank=True, default="", max_length=4)),
                (
                    "receiver_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "receiver_rel",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
                "ordering": ["-created_at"],
            },
        ),
    ]
